# This is the configuration used to check the rubocop-vendor source code.

inherit_from: .rubocop_todo.yml
require:
  - rubocop/cop/internal_affairs
  - rubocop-vendor
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "tmp/**/*"
  TargetRubyVersion: 2.7

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"
    - "rubocop-vendor.gemspec"

Layout/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - lib/rubocop-vendor.rb

RSpec/FactoryBot/CreateList:
  Enabled: false

RSpec/NestedGroups:
  Max: 7

Style/Documentation:
  Exclude:
    - lib/rubocop/cop/vendor_cops.rb

Style/NumericPredicate:
  Exclude:
    - tasks/cops_documentation.rake

Style/FormatStringToken:
  # Because we parse a lot of source codes from strings. Percent arrays
  # look like unannotated format string tokens to this cop.
  Exclude:
    - spec/**/*
