site_name: "RuboCop Vendor: Vendor integration analysis for your projects"
repo_url: https://github.com/wealthsimple/rubocop-vendor
edit_uri: edit/master/manual/
copyright: "Copyright &copy; 2019 RuboCop contributors"
docs_dir: manual
pages:
- Home: index.md
- Installation: installation.md
- Usage: usage.md
- Cops: cops_vendor.md
markdown_extensions:
  - admonition
theme: readthedocs
