version: 2.1

jobs:
  rake_default:
    parameters:
      image:
        description: "Name of the Docker image."
        type: string
        default: "circleci/ruby"
    docker:
      - image: << parameters.image >>
    environment:
      # CircleCI container has two cores, but Ruby can see 32 cores. So we
      # configure test-queue.
      # See https://github.com/tmm1/test-queue#environment-variables
      TEST_QUEUE_WORKERS: 2
      JRUBY_OPTS: "--dev -J-Xmx1000M"
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake

  release:
    parameters:
      image:
        description: "Name of the Docker image."
        type: string
        default: "circleci/ruby:2.4"
    docker:
      - image: << parameters.image >>
    environment:
      # CircleCI container has two cores, but Ruby can see 32 cores. So we
      # configure test-queue.
      # See https://github.com/tmm1/test-queue#environment-variables
      TEST_QUEUE_WORKERS: 2
    steps:
      - add_ssh_keys:
          fingerprints:
            - "46:b5:cb:ee:57:dc:14:95:31:be:12:13:4f:11:94:a4"
      - checkout
      - run: bundle install
      - run:
          name: Release to rubygems.org
          command: |
            echo "github.com,192.30.253.112 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >> ~/.ssh/known_hosts
            mkdir ~/.gem
            echo ":rubygems_api_key: ${RUBYGEMS_API_KEY}" >> ~/.gem/credentials
            chmod 600 ~/.gem/credentials
            bundle exec rake release

workflows:
  build:
    jobs:
      - rake_default:
          name: Ruby 2.4
          image: circleci/ruby:2.4
      - rake_default:
          name: Ruby 2.5
          image: circleci/ruby:2.5
      - rake_default:
          name: Ruby 2.6
          image: circleci/ruby:2.6
      - rake_default:
          name: Ruby HEAD
          image: rubocophq/circleci-ruby-snapshot:latest # Nightly snapshot build
      - rake_default:
          name: JRuby 9.2
          image: circleci/jruby:9.2
      - release:
          context: wealthsimple
          filters:
            branches:
              only: master
          requires:
          - Ruby 2.4

